export type WorkerRarity = "common" | "rare" | "elite";

export interface WorkerDef {
  id: string;           // same as slug
  slug: string;         // image filename without extension
  name: string;
  description: string;
  image: string;        // /images/hooker/{slug}.jpg
  hire_price: number;
  hire_uses_crypto: boolean;
  earnings_per_hour: number;
  traits: string[];
  rarity: WorkerRarity;
  required_level: number; // player level required to hire
  stats: {
    attractiveness: number; // 0-100, drives client rate
    stamina: number;        // 0-100, work capacity
    mood: number;           // 0-100, price multiplier
    charisma: number;       // 0-100, bonus income
  };
  order: number;
}

export const RARITY_CONFIG: Record<
  WorkerRarity,
  { label: string; color: string; border: string; glow: string; activeGlow: string; badge: string; star: string }
> = {
  common: {
    label: "Comum",
    color: "text-gray-400",
    border: "border-gray-600/50",
    glow: "",
    activeGlow: "shadow-[0_0_30px_rgba(150,150,150,0.25)]",
    badge: "bg-gray-800 text-gray-300",
    star: "⬜",
  },
  rare: {
    label: "Rara",
    color: "text-blue-400",
    border: "border-blue-500/60",
    glow: "shadow-[0_0_20px_rgba(59,130,246,0.25)]",
    activeGlow: "shadow-[0_0_60px_rgba(59,130,246,0.6)]",
    badge: "bg-blue-900/60 text-blue-300",
    star: "🔵",
  },
  elite: {
    label: "Elite",
    color: "text-amber-400",
    border: "border-amber-500/70",
    glow: "shadow-[0_0_30px_rgba(245,158,11,0.35)]",
    activeGlow: "shadow-[0_0_80px_rgba(245,158,11,0.7)]",
    badge: "bg-amber-900/70 text-amber-300",
    star: "✦",
  },
};

export const WORKER_DEFS: WorkerDef[] = [
  {
    id: "instagram_model", slug: "instagram_model",
    name: "Kylie",
    description: "100k seguidores. Cada visita ao teu estabelecimento vale mais do que parece. Os clientes pagam só para dizer que a conhecem.",
    image: "/images/hooker/instagram_model.jpg",
    hire_price: 100000, hire_uses_crypto: true,
    earnings_per_hour: 520,
    traits: ["Influencer", "Premium", "Famosa"],
    rarity: "elite",
    required_level: 103,
    stats: { attractiveness: 96, stamina: 68, mood: 90, charisma: 95 },
    order: 1,
  },
  {
    id: "sra_perfeita", slug: "sra_perfeita",
    name: "Perfeita",
    description: "O nome não é coincidência. Raro existir outra igual no mercado. Quem a conhece não consegue descrever — apenas recomendar.",
    image: "/images/hooker/sra_perfeita.jpg",
    hire_price: 120000, hire_uses_crypto: true,
    earnings_per_hour: 550,
    traits: ["Perfeita", "Única", "Lendária"],
    rarity: "elite",
    required_level: 106,
    stats: { attractiveness: 97, stamina: 85, mood: 92, charisma: 98 },
    order: 2,
  },
  {
    id: "modelo_russa", slug: "modelo_russa",
    name: "Katya",
    description: "Ex-modelo de Moscovo. A elegância russa tem um preço — e vale cada cêntimo. Chegou há seis meses e já tem lista de espera.",
    image: "/images/hooker/modelo_russa.jpg",
    hire_price: 80000, hire_uses_crypto: false,
    earnings_per_hour: 460,
    traits: ["Elegante", "Premium", "Gelada"],
    rarity: "elite",
    required_level: 97,
    stats: { attractiveness: 93, stamina: 75, mood: 82, charisma: 89 },
    order: 3,
  },
  {
    id: "grandes_assets", slug: "grandes_assets",
    name: "Valentina",
    description: "Não precisa de apresentação. A fama precede-a. Os clientes de alto valor pedem especificamente por ela.",
    image: "/images/hooker/grandes_assets.jpg",
    hire_price: 75000, hire_uses_crypto: false,
    earnings_per_hour: 450,
    traits: ["Carismática", "Premium", "Notória"],
    rarity: "elite",
    required_level: 94,
    stats: { attractiveness: 94, stamina: 78, mood: 86, charisma: 92 },
    order: 4,
  },
  {
    id: "enfermeira_da_twitch", slug: "enfermeira_da_twitch",
    name: "Nurse",
    description: "Famosa na internet, agora disponível ao vivo. Os fãs pagam premium só para a ver. O teu negócio nunca teve tanta atenção.",
    image: "/images/hooker/enfermeira_da_twitch.jpg",
    hire_price: 90000, hire_uses_crypto: true,
    earnings_per_hour: 500,
    traits: ["Famosa", "Online", "Carismática"],
    rarity: "elite",
    required_level: 100,
    stats: { attractiveness: 92, stamina: 70, mood: 88, charisma: 96 },
    order: 5,
  },
  {
    id: "brazileira", slug: "brazileira",
    name: "Yasmin",
    description: "O calor do Brasil num estabelecimento do norte. Traz alegria aonde quer que vá. Clientes voltam sempre — e trazem amigos.",
    image: "/images/hooker/brazileira.jpg",
    hire_price: 65000, hire_uses_crypto: false,
    earnings_per_hour: 420,
    traits: ["Extrovertida", "Carismática", "Radiante"],
    rarity: "elite",
    required_level: 85,
    stats: { attractiveness: 90, stamina: 82, mood: 90, charisma: 91 },
    order: 6,
  },
  {
    id: "neguinha_cara", slug: "neguinha_cara",
    name: "Luxara",
    description: "Cobra o que quer. E os clientes pagam sem questionar. Tem uma presença que nenhum dinheiro consegue ensinar.",
    image: "/images/hooker/neguinha_cara.jpg",
    hire_price: 70000, hire_uses_crypto: false,
    earnings_per_hour: 430,
    traits: ["Premium", "Confiante", "Intimidante"],
    rarity: "elite",
    required_level: 88,
    stats: { attractiveness: 91, stamina: 78, mood: 85, charisma: 90 },
    order: 7,
  },
  {
    id: "princessa", slug: "princessa",
    name: "Isabella",
    description: "Trata-se como realeza. Os clientes também a tratam. Há um protocolo para marcar com ela — e os clientes adoram isso.",
    image: "/images/hooker/princessa.jpg",
    hire_price: 72000, hire_uses_crypto: false,
    earnings_per_hour: 440,
    traits: ["Elegante", "Exigente", "Real"],
    rarity: "elite",
    required_level: 91,
    stats: { attractiveness: 89, stamina: 68, mood: 84, charisma: 88 },
    order: 8,
  },
  {
    id: "gotica_tetus2", slug: "gotica_tetus2",
    name: "Lilith",
    description: "Há uma lista de espera apenas para falar com ela. Não trabalha para todos — escolhe os seus clientes. E isso vale ouro.",
    image: "/images/hooker/gotica_tetus2.jpg",
    hire_price: 58000, hire_uses_crypto: false,
    earnings_per_hour: 380,
    traits: ["Lendária", "Misteriosa", "Seletiva"],
    rarity: "elite",
    required_level: 82,
    stats: { attractiveness: 88, stamina: 76, mood: 72, charisma: 87 },
    order: 9,
  },
  {
    id: "acrobata_flexivel", slug: "acrobata_flexivel",
    name: "Jade",
    description: "A flexibilidade dela é lendária nos bastidores. Os clientes pagam extra só para vê-la chegar. Cada sessão é uma performance.",
    image: "/images/hooker/acrobata_flexivel.jpg",
    hire_price: 55000, hire_uses_crypto: false,
    earnings_per_hour: 380,
    traits: ["Flexível", "Artista", "Memorável"],
    rarity: "elite",
    required_level: 79,
    stats: { attractiveness: 88, stamina: 92, mood: 80, charisma: 83 },
    order: 10,
  },
  {
    id: "ruiva_safada", slug: "ruiva_safada",
    name: "Scarlett",
    description: "A ruiva que toda a gente conhece. Temperamento próprio, resultados garantidos. Uma sessão com ela e os clientes contam a história.",
    image: "/images/hooker/ruiva_safada.jpg",
    hire_price: 32000, hire_uses_crypto: false,
    earnings_per_hour: 295,
    traits: ["Picante", "Impulsiva", "Irresistível"],
    rarity: "rare",
    required_level: 70,
    stats: { attractiveness: 85, stamina: 78, mood: 70, charisma: 82 },
    order: 11,
  },
  {
    id: "asian_rabbit", slug: "asian_rabbit",
    name: "Mei",
    description: "Tem um sorriso que vale ouro. Vinda de longe, com uma história para contar. Os clientes ficam fascinados antes mesmo de a conhecer.",
    image: "/images/hooker/asian_rabbit.jpg",
    hire_price: 35000, hire_uses_crypto: false,
    earnings_per_hour: 310,
    traits: ["Misteriosa", "Discreta", "Exótica"],
    rarity: "rare",
    required_level: 73,
    stats: { attractiveness: 84, stamina: 78, mood: 82, charisma: 80 },
    order: 12,
  },
  {
    id: "chinoca_striper", slug: "chinoca_striper",
    name: "Xiao",
    description: "Treinada nos melhores clubes de Macau. Sabe como fazer um espetáculo que os clientes não esquecem tão facilmente.",
    image: "/images/hooker/chinoca_striper.jpg",
    hire_price: 30000, hire_uses_crypto: false,
    earnings_per_hour: 300,
    traits: ["Elegante", "Performista", "Disciplinada"],
    rarity: "rare",
    required_level: 67,
    stats: { attractiveness: 86, stamina: 80, mood: 76, charisma: 81 },
    order: 13,
  },
  {
    id: "russa_safadad", slug: "russa_safadad",
    name: "Vika",
    description: "Não deixa ninguém indiferente. Alta energia, altos rendimentos. Tem uma reputação que antecede qualquer apresentação.",
    image: "/images/hooker/russa_safadad.jpg",
    hire_price: 36000, hire_uses_crypto: false,
    earnings_per_hour: 310,
    traits: ["Energética", "Atrevida", "Imparável"],
    rarity: "rare",
    required_level: 76,
    stats: { attractiveness: 86, stamina: 82, mood: 74, charisma: 84 },
    order: 14,
  },
  {
    id: "19anos_estudante_direito", slug: "19anos_estudante_direito",
    name: "Sofia",
    description: "Estudante de direito que precisava de um extra. Sabe como negociar qualquer coisa. Inteligente, ambiciosa e sem escrúpulos.",
    image: "/images/hooker/19anos_estudante_direito.jpg",
    hire_price: 28000, hire_uses_crypto: false,
    earnings_per_hour: 280,
    traits: ["Inteligente", "Ambiciosa", "Persuasiva"],
    rarity: "rare",
    required_level: 61,
    stats: { attractiveness: 82, stamina: 65, mood: 78, charisma: 79 },
    order: 15,
  },
  {
    id: "russa", slug: "russa",
    name: "Nadia",
    description: "A frieza russa esconde um fogo interior. Os clientes voltam para descobrir mais. Nunca diz mais do que o necessário.",
    image: "/images/hooker/russa.jpg",
    hire_price: 28000, hire_uses_crypto: false,
    earnings_per_hour: 280,
    traits: ["Misteriosa", "Reservada", "Intensa"],
    rarity: "rare",
    required_level: 64,
    stats: { attractiveness: 82, stamina: 76, mood: 68, charisma: 77 },
    order: 16,
  },
  {
    id: "estudante_europea", slug: "estudante_europea",
    name: "Elena",
    description: "De Praga para cá. Tem a classe europeia que os clientes de alto valor procuram. Fala três línguas e usa isso a seu favor.",
    image: "/images/hooker/estudante_europea.jpg",
    hire_price: 27000, hire_uses_crypto: false,
    earnings_per_hour: 285,
    traits: ["Elegante", "Culta", "Ambiciosa"],
    rarity: "rare",
    required_level: 58,
    stats: { attractiveness: 83, stamina: 72, mood: 79, charisma: 78 },
    order: 17,
  },
  {
    id: "gotica_tets", slug: "gotica_tets",
    name: "Morgana",
    description: "A escuridão atrai. Os clientes que a procuram nunca mais querem outra. Tem um nicho muito específico — e muito fiel.",
    image: "/images/hooker/gotica_tets.jpg",
    hire_price: 26000, hire_uses_crypto: false,
    earnings_per_hour: 265,
    traits: ["Misteriosa", "Única", "Nicho"],
    rarity: "rare",
    required_level: 55,
    stats: { attractiveness: 79, stamina: 74, mood: 65, charisma: 76 },
    order: 18,
  },
  {
    id: "acrobata", slug: "acrobata",
    name: "Luna",
    description: "Ex-ginasta que trocou os holofotes por algo mais lucrativo. A resistência física dela é incomparável. Nunca se queixa.",
    image: "/images/hooker/acrobata.jpg",
    hire_price: 22000, hire_uses_crypto: false,
    earnings_per_hour: 260,
    traits: ["Flexível", "Resistente", "Atlética"],
    rarity: "rare",
    required_level: 43,
    stats: { attractiveness: 75, stamina: 95, mood: 72, charisma: 71 },
    order: 19,
  },
  {
    id: "lider_claque", slug: "lider_claque",
    name: "Raquel",
    description: "Lidera multidões. O teu negócio nunca esteve tão animado. Sabe criar uma atmosfera que os clientes pagam para respirar.",
    image: "/images/hooker/lider_claque.jpg",
    hire_price: 23000, hire_uses_crypto: false,
    earnings_per_hour: 275,
    traits: ["Extrovertida", "Motivadora", "Animada"],
    rarity: "rare",
    required_level: 46,
    stats: { attractiveness: 77, stamina: 85, mood: 88, charisma: 82 },
    order: 20,
  },
  {
    id: "preta_pau", slug: "preta_pau",
    name: "Ebony",
    description: "Profissional de alto calibre. Sabe exatamente o que vale no mercado e não aceita menos do que isso. Experiência garantida.",
    image: "/images/hooker/preta_pau.jpg",
    hire_price: 25000, hire_uses_crypto: false,
    earnings_per_hour: 270,
    traits: ["Profissional", "Direta", "Confiante"],
    rarity: "rare",
    required_level: 52,
    stats: { attractiveness: 80, stamina: 80, mood: 78, charisma: 78 },
    order: 21,
  },
  {
    id: "tia_cascais3", slug: "tia_cascais3",
    name: "Leonor",
    description: "A mais refinada das três de Cascais. Uma reputação que atrai clientela seleta que não se mistura com qualquer coisa.",
    image: "/images/hooker/tia_cascais3.jpg",
    hire_price: 20000, hire_uses_crypto: false,
    earnings_per_hour: 250,
    traits: ["Refinada", "Elegante", "Selectiva"],
    rarity: "rare",
    required_level: 40,
    stats: { attractiveness: 76, stamina: 70, mood: 80, charisma: 74 },
    order: 22,
  },
  {
    id: "atleta", slug: "atleta",
    name: "Diana",
    description: "A disciplina atlética aplica-se a tudo o que faz. Clientes nunca saem desiludidos. A resistência dela é a melhor do negócio.",
    image: "/images/hooker/atleta.jpg",
    hire_price: 24000, hire_uses_crypto: false,
    earnings_per_hour: 270,
    traits: ["Determinada", "Resistente", "Focada"],
    rarity: "rare",
    required_level: 49,
    stats: { attractiveness: 78, stamina: 98, mood: 75, charisma: 73 },
    order: 23,
  },
  {
    id: "loira_do_pau", slug: "loira_do_pau",
    name: "Stacy",
    description: "Clássica. Eficiente. Sempre disponível. Um pilar do estabelecimento que os clientes regulares já conhecem pelo nome.",
    image: "/images/hooker/loira_do_pau.jpg",
    hire_price: 12000, hire_uses_crypto: false,
    earnings_per_hour: 155,
    traits: ["Confiável", "Clássica", "Regular"],
    rarity: "common",
    required_level: 34,
    stats: { attractiveness: 66, stamina: 74, mood: 68, charisma: 62 },
    order: 24,
  },
  {
    id: "neguinha", slug: "neguinha",
    name: "Nia",
    description: "Energética e dedicada. Os clientes pedem sempre para voltar. Tem uma naturalidade que ninguém consegue fingir.",
    image: "/images/hooker/neguinha.jpg",
    hire_price: 13000, hire_uses_crypto: false,
    earnings_per_hour: 160,
    traits: ["Energética", "Simpática", "Natural"],
    rarity: "common",
    required_level: 37,
    stats: { attractiveness: 68, stamina: 82, mood: 76, charisma: 66 },
    order: 25,
  },
  {
    id: "russa2", slug: "russa2",
    name: "Olga",
    description: "Segunda opção nunca soou tão bem. Competente, discreta, e faz o trabalho sem drama. Um ativo silencioso do negócio.",
    image: "/images/hooker/russa2.jpg",
    hire_price: 11500, hire_uses_crypto: false,
    earnings_per_hour: 148,
    traits: ["Discreta", "Competente", "Silenciosa"],
    rarity: "common",
    required_level: 31,
    stats: { attractiveness: 63, stamina: 74, mood: 66, charisma: 60 },
    order: 26,
  },
  {
    id: "cadela", slug: "cadela",
    name: "Bia",
    description: "Tem atitude própria. Às vezes rebelde, mas os clientes adoram. Uma instabilidade calculada que acaba por fidelizar.",
    image: "/images/hooker/cadela.jpg",
    hire_price: 10000, hire_uses_crypto: false,
    earnings_per_hour: 140,
    traits: ["Teimosa", "Atrevida", "Imprevisível"],
    rarity: "common",
    required_level: 16,
    stats: { attractiveness: 65, stamina: 68, mood: 58, charisma: 63 },
    order: 27,
  },
  {
    id: "casual_1", slug: "casual_1",
    name: "Ana",
    description: "Parece completamente normal. E é exatamente isso que a torna especial. Os clientes relaxam com ela de uma forma que não conseguem explicar.",
    image: "/images/hooker/casual_1.jpg",
    hire_price: 10000, hire_uses_crypto: false,
    earnings_per_hour: 145,
    traits: ["Simpática", "Natural", "Reconfortante"],
    rarity: "common",
    required_level: 19,
    stats: { attractiveness: 62, stamina: 72, mood: 70, charisma: 64 },
    order: 28,
  },
  {
    id: "cabra", slug: "cabra",
    name: "Carla",
    description: "Sabe trabalhar. Não faz perguntas, não cria problemas. Um investimento sólido e previsível. O que todo o negócio precisa.",
    image: "/images/hooker/cabra.jpg",
    hire_price: 11000, hire_uses_crypto: false,
    earnings_per_hour: 150,
    traits: ["Discreta", "Eficiente", "Estável"],
    rarity: "common",
    required_level: 28,
    stats: { attractiveness: 60, stamina: 70, mood: 62, charisma: 58 },
    order: 29,
  },
  {
    id: "timida", slug: "timida",
    name: "Sara",
    description: "Tímida só no nome. Com tempo e carinho, floresce como nenhuma outra. Os clientes mais pacientes voltam sempre por ela.",
    image: "/images/hooker/timida.jpg",
    hire_price: 10500, hire_uses_crypto: false,
    earnings_per_hour: 140,
    traits: ["Tímida", "Leal", "Crescente"],
    rarity: "common",
    required_level: 25,
    stats: { attractiveness: 62, stamina: 72, mood: 74, charisma: 60 },
    order: 30,
  },
  {
    id: "tia_cascais", slug: "tia_cascais",
    name: "Cristina",
    description: "Cascais no nome, charme genuíno na prática. A clientela mais velha adora. Traz um conforto que nenhuma jovem consegue replicar.",
    image: "/images/hooker/tia_cascais.jpg",
    hire_price: 10000, hire_uses_crypto: false,
    earnings_per_hour: 138,
    traits: ["Caseira", "Reconfortante", "Fiel"],
    rarity: "common",
    required_level: 22,
    stats: { attractiveness: 60, stamina: 68, mood: 78, charisma: 65 },
    order: 31,
  },
  {
    id: "tia_cascais2", slug: "tia_cascais2",
    name: "Mafalda",
    description: "A segunda de Cascais, mas não em qualidade. Tem um conjunto de clientes fiéis que não trocam por nada.",
    image: "/images/hooker/tia_cascais2.jpg",
    hire_price: 8500, hire_uses_crypto: false,
    earnings_per_hour: 125,
    traits: ["Caseira", "Simpática", "Discreta"],
    rarity: "common",
    required_level: 4,
    stats: { attractiveness: 56, stamina: 66, mood: 75, charisma: 60 },
    order: 32,
  },
  {
    id: "tia_cabedal", slug: "tia_cabedal",
    name: "Fátima",
    description: "Experiência conta. Décadas de conhecimento condensado num sorriso. Os novatos subestimam-na. Os clientes antigos sabem melhor.",
    image: "/images/hooker/tia_cabedal.jpg",
    hire_price: 9000, hire_uses_crypto: false,
    earnings_per_hour: 130,
    traits: ["Experiente", "Fiel", "Sábia"],
    rarity: "common",
    required_level: 7,
    stats: { attractiveness: 58, stamina: 70, mood: 82, charisma: 68 },
    order: 33,
  },
  {
    id: "limpesa", slug: "limpesa",
    name: "Rosa",
    description: "Começou a limpar o estabelecimento. Ficou pelo negócio. Tem um charme caseiro que agrada a uma clientela muito específica.",
    image: "/images/hooker/limpesa.jpg",
    hire_price: 8000, hire_uses_crypto: false,
    earnings_per_hour: 125,
    traits: ["Honesta", "Simpática", "Dedicada"],
    rarity: "common",
    required_level: 1,
    stats: { attractiveness: 55, stamina: 80, mood: 72, charisma: 58 },
    order: 34,
  },
  {
    id: "alcolica", slug: "alcolica",
    name: "Vera",
    description: "Funciona melhor depois do terceiro copo. Os clientes gostam da autenticidade dela. Nunca sóbria, nunca previsível.",
    image: "/images/hooker/alcolica.jpg",
    hire_price: 9000, hire_uses_crypto: false,
    earnings_per_hour: 130,
    traits: ["Descontraída", "Imprevisível", "Autêntica"],
    rarity: "common",
    required_level: 10,
    stats: { attractiveness: 55, stamina: 40, mood: 60, charisma: 62 },
    order: 35,
  },
  {
    id: "mulher_gorda", slug: "mulher_gorda",
    name: "Bertha",
    description: "Um nicho muito específico com clientela de retorno garantido. Autenticidade pura. Os números são consistentes há anos.",
    image: "/images/hooker/mulher_gorda.jpg",
    hire_price: 9500, hire_uses_crypto: false,
    earnings_per_hour: 135,
    traits: ["Autêntica", "Fiel", "Consistente"],
    rarity: "common",
    required_level: 13,
    stats: { attractiveness: 58, stamina: 65, mood: 80, charisma: 65 },
    order: 36,
  },
];
